### PR TITLE
add missing nil support

### PR DESCRIPTION
**Pull request by bkilshaw**
Added support so that the Human, Percentage, and SI modules accept nil as a value.

### CODE REVIEW

**Review by danielberkompas — APPROVED** [review]
Looks good, thanks! ⭐

**Comment by zorn-allovue** [comment]
@danielberkompas It might be more helpful and explicit if the functions that are accepting of these `nil` argument values make sure `nil` is defined as a valid incoming argument value in the typesepcs as well.

Personal aside, I question if it is a good idea to accept `nil` for these functions. If the call sites do not have confidence about their variables I'm not sure the supporting libraries should have to be so accepting of `nil`. I'd rather the library be explicit about only offering conversion of known Number values. 🤷‍♂️ 

A kind of nitpicky take, and I only offer it as an additional perspective. Thanks for the work on this library.

**Comment by bkilshaw** [comment]
> @danielberkompas It might be more helpful and explicit if the functions that are accepting of these `nil` argument values make sure `nil` is defined as a valid incoming argument value in the typesepcs as well.
> 
> Personal aside, I question if it is a good idea to accept `nil` for these functions. If the call sites do not have confidence about their variables I'm not sure the supporting libraries should have to be so accepting of `nil`. I'd rather the library be explicit about only offering conversion of known Number values. 🤷‍♂️
> 
> A kind of nitpicky take, and I only offer it as an additional perspective. Thanks for the work on this library.

I honestly don't have a strong opinion either way; some of the other modules accept (and return) nil, so I was aligning the other modules so they all behaved the same. Removing the nil support in the other modules would be a breaking change though. 

In our use case we're using Number directly in our HEEX templates, some fields nave a nil value, so  something like this ended up being useful:

```
<table>
   <tr :for={quote <- quote_requests}>
      <td><%= quote.name %></td>
      <td><%= Number.Currency.number_to_currency(quote.price) %>
   </tr>
</table>
```

We needed the same for the Percentage module hence the PR. We can definitely check the value first, just sharing the use case for accepting nil.

**Comment by danielberkompas** [comment]
I chose to accept nil here because it matches the behavior of `ActionView::NumberHelper`. Since `number` advertises itself as having a very similar API, I think it makes sense to follow `ActionView::NumberHelper`, to reduce surprises that former Rails developers in particular will experience when using the library.

Thanks for the feedback both of you!

**Comment by zorn-allovue** [comment]
Thanks for the reply and the context. 👍

**Comment by hissssst** [comment]
@bkilshaw , check this out

```heex
<table>
   <tr :for={quote <- quote_requests}>
      <td><%= quote.name %></td>
      <td><%= quote.price && Number.Currency.number_to_currency(quote.price) %>
   </tr>
</table>
```

**Comment by hissssst** [comment]
And I also think that this is a breaking change. Functions used to raise in case of `nil`, but now they work and return `nil`. This is breaking the contract and requires a major version bump

**Pull request merged**
